language: node_js

node_js:
 - "0.10"

cache:
  directories:
    - node_modules
    - bower_components

env:
  global:
    secure: "Q5ys/ZVItkWDGQdehcWbSdEYgWTGVgh5lpTIvm6EVYAHmCrccocANPhIXcjLkcuvaJksL0MXDafX6hY9RbecmJm4kRyBeap5rsKDUmVKZOl/xuZaBvxG8sQ8vbPsnh5qPe9ilWo7gIhabGD37mfEL+efNvuyd4aVJNQnV1hWRDI="

before_install:
 - npm install -g grunt grunt-cli bower
 - bower install

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
 - ./node_modules/karma/bin/karma start --single-run --browsers Firefox

after_success:
 - npm install -g codeclimate-test-reporter
 - ./coverage.sh