language: node_js

node_js:
 - "0.11"
 - "0.10"

before_install:
 - npm install -g grunt grunt-cli bower
 - bower install

before_script:
 - npm install -g karma
script:
 - karma start --single-run --browsers Firefox
